import type { Product } from "@/lib/products";
import deck from "@/assets/hero-deck.jpg";
import surfboard from "@/assets/craft-surfboard.jpg";
import apparel from "@/assets/apparel.jpg";
import accessories from "@/assets/accessories.jpg";

/**
 * Static fallback catalog used only when the live product fetch fails
 * (offline, RLS misconfig, or backend downtime). Keeps the storefront
 * browsable so the customer never sees an empty shop.
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-1",
    slug: "liminal-classic-deck",
    title: "Liminal Classic Deck",
    department: "skate",
    product_type: "deck",
    target_group: "unisex",
    description: "7-ply maple, medium concave.",
    details: [],
    price: 60,
    sale_price: null,
    colour: "black",
    sizes: ["8.0", "8.25", "8.5"],
    stock_count: 12,
    images: [deck],
    tags: ["featured"],
    specs: {},
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    slug: "coastline-fish",
    title: "Coastline Fish 5'8\"",
    department: "surf",
    product_type: "surfboard",
    target_group: "unisex",
    description: "Twin-fin retro fish for mushy waves.",
    details: [],
    price: 620,
    sale_price: null,
    colour: "white",
    sizes: [],
    stock_count: 3,
    images: [surfboard],
    tags: ["featured"],
    specs: {},
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    slug: "core-heavy-tee",
    title: "Core Heavy Tee",
    department: "clothing",
    product_type: "tee",
    target_group: "unisex",
    description: "230gsm mid-weight cotton.",
    details: [],
    price: 35,
    sale_price: null,
    colour: "black",
    sizes: ["S", "M", "L", "XL"],
    stock_count: 50,
    images: [apparel],
    tags: ["featured"],
    specs: {},
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    slug: "beach-tote",
    title: "Beach Tote",
    department: "accessories",
    product_type: "bag",
    target_group: "unisex",
    description: "Sand-resistant canvas.",
    details: [],
    price: 45,
    sale_price: null,
    colour: "brown",
    sizes: [],
    stock_count: 20,
    images: [accessories],
    tags: ["featured"],
    specs: {},
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
