// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Resolve Supabase URL and anon key.
 *
 * Browser bundle (Vite) reads `VITE_*` env vars. Server runtime reads the
 * unprefixed names. We support both so the same client module can be imported
 * from either environment.
 *
 * NOTE: this file intentionally never throws and never blocks rendering when
 * the keys are missing. The proxy at the bottom of the file returns a safe
 * no-op stub that keeps the React tree mountable while `isSupabaseConfigured`
 * reports `false`. The `BackendBanner` component in `__root.tsx` is what
 * surfaces a helpful warning to the developer / user.
 */
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "";

const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ??
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  process.env.SUPABASE_ANON_KEY ??
  process.env.SUPABASE_PUBLISHABLE_KEY ??
  "";

/**
 * Public flag the UI can read to decide whether to:
 *   - show the "Backend configuration missing" banner, and
 *   - disable login / signup / data-fetching UI instead of crashing.
 */
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY);

function createSupabaseClient(): SupabaseClient<Database> | null {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_ANON_KEY ? ["VITE_SUPABASE_ANON_KEY"] : []),
    ];
    // Helpful developer-facing warning; never throws.
    // eslint-disable-next-line no-console
    console.warn(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
        `Authentication and database features are disabled until set. ` +
        `Add them via the project's API Keys tab (or .env.local for local dev).`,
    );
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: SupabaseClient<Database> | null | undefined;

/**
 * Proxy Supabase client. When env vars are missing this proxy returns:
 *   - `.auth.*`         → safe no-op stubs that never throw and surface a
 *                           "Backend not configured" error message
 *   - `.from(...)`      → a query-builder stub that resolves to empty data
 *   - anything else     → a chained no-op
 *
 * This guarantees React renders normally while the banner informs the user.
 */
export const supabase: SupabaseClient<Database> = new Proxy(
  {} as SupabaseClient<Database>,
  {
    get(_target, prop, receiver) {
      if (_supabase === undefined) _supabase = createSupabaseClient();
      if (_supabase === null) {
        if (prop === "auth") {
          return {
            getSession: async () => ({
              data: { session: null },
              error: null,
            }),
            onAuthStateChange: () => ({
              data: { subscription: { unsubscribe: () => {} } },
            }),
            signInWithPassword: async () => ({
              data: { user: null, session: null },
              error: { message: "Backend not configured" },
            }),
            signUp: async () => ({
              data: { user: null, session: null },
              error: { message: "Backend not configured" },
            }),
            signOut: async () => ({ error: null }),
            getUser: async () => ({ data: { user: null }, error: null }),
            admin: {
              updateUserById: async () => ({
                data: {},
                error: { message: "Backend not configured" },
              }),
            },
          };
        }
        // For .from() and any other PostgREST/query builder, return a proxy that
        // ultimately resolves to empty data without throwing.
        return new Proxy(
          {},
          {
            get: () => () =>
              new Proxy(
                {},
                {
                  get: () => () =>
                    Promise.resolve({ data: null, error: null, count: 0 }),
                },
              ),
          },
        );
      }
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
