// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function resolveEnv() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;
  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = resolveEnv();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["VITE_SUPABASE_ANON_KEY"] : []),
    ];
    console.warn(`[Supabase] Missing env var(s): ${missing.join(", ")}. Client disabled.`);
    return createNoopClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createNoopClient(): SupabaseClient<Database> {
  const reject = () => Promise.resolve({ data: null, error: { message: "Supabase not configured" } as never });
  const chain = new Proxy(() => chain, {
    get: () => chain,
    apply: () => ({ data: null, error: { message: "Supabase not configured" } as never }),
  });
  return {
    auth: { getSession: reject, getUser: reject, onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }) } as never,
    from: () => chain,
    storage: { from: () => chain } as never,
    channel: () => chain,
  } as unknown as SupabaseClient<Database>;
}

let _supabase: SupabaseClient<Database> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
