// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient(): SupabaseClient<Database> | null {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY / SUPABASE_ANON_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. ` +
        `The site will run in a degraded mode — authentication and database features will be unavailable. ` +
        `Check your Vercel/Lovable environment variables.`,
    );
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: SupabaseClient<Database> | null | undefined;

export const supabase: SupabaseClient<Database> = new Proxy(
  {} as SupabaseClient<Database>,
  {
    get(_, prop, receiver) {
      if (_supabase === undefined) _supabase = createSupabaseClient();
      if (_supabase === null) {
        // Return a no-op stub for any property access when env vars are missing.
        // This prevents crashes while making it clear the backend is unavailable.
        if (prop === "auth") {
          return {
            getSession: async () => ({ data: { session: null }, error: null }),
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            signInWithPassword: async () => ({ data: { user: null }, error: { message: "Backend not configured" } }),
            signUp: async () => ({ data: { user: null }, error: { message: "Backend not configured" } }),
            signOut: async () => ({ error: null }),
            getUser: async () => ({ data: { user: null }, error: null }),
            admin: { updateUserById: async () => ({ data: {}, error: { message: "Backend not configured" } }) },
          };
        }
        // For .from() and other query builders, return a proxy that resolves to empty
        return new Proxy(
          {},
          {
            get: () => () =>
              new Proxy(
                {},
                {
                  get: () => () =>
                    Promise.resolve({ data: null, error: null, count: 0 }),
                },
              ),
          },
        );
      }
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
